00003951_DBSD_CW2/Controllers/FlowerController.cs
using _00003951_DBSD_CW2.DataAccess;
using _00003951_DBSD_CW2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _00003951_DBSD_CW2.Controllers
{
    public class FlowerController : BaseController
    {
        // GET: Vacancy
        public ActionResult Index(int? fCategory, string fName, string fDescription)
        {
            FlowerManager manager = new FlowerManager();
            FlowerCategoryManager categoryManager = new FlowerCategoryManager();
            IList<Flower> list = manager.FilterFlowers(fCategory, fName, fDescription);
            IList<FlowerCategory> categories = categoryManager.GetFlowerCategories();
            foreach(Flower item in list)
            {
                item.FlowerCategory = categories.First(d => d.Id == item.FlowerCategoryId);
            }
            ViewBag.fTitle = fName;
            ViewBag.fDescription = fDescription;
            ViewBag.fCategory = fCategory;
            ViewBag.categories = categories;
            return View(list);
        }
    }
}

00003951_DBSD_CW2/Controllers/OrderController.cs
using _00003951_DBSD_CW2.DataAccess;
using _00003951_DBSD_CW2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace _00003951_DBSD_CW2.Controllers
{
    [Authorize]
    public class OrderController : BaseController
    {
        // GET: Order
        public ActionResult Index()
        {

            Customer user = this.getCustomer();
            FlowerOrderManager manager = new FlowerOrderManager();
            IList<FlowerOrder> list = manager.GetFlowerOrdersByCustomer(user.Id);

            return View(list);
        }

        // GET: Order/Details/5
        public ActionResult Details(int id)
        {
            FlowerOrderManager manager = new FlowerOrderManager();
            FlowerOrder model = manager.GetFlowerOrderById(id);

            IList<Flower> flowers = new FlowerManager().GetFlowers();
            
            model.OrderItems = manager.GetOrderItems(model.Id);
            foreach (OrderItem orderItem in model.OrderItems)
            {
                orderItem.Flower = flowers.First(f => f.Id == orderItem.FlowerId);
            }

            return View(model);
        }

        // GET: Order/Checkout
        public ActionResult Checkout()
        {
            return View();
        }

        // POST: Order/Checkout
        [HttpPost]
        public ActionResult Checkout(FlowerOrder order)
        {
            try
            {
                Customer user = this.getCustomer();
                ShoppingCartManager cartManager = new ShoppingCartManager();
                FlowerOrderManager orderManager = new FlowerOrderManager();
                order.CustomerId = user.Id;
                order.CreatedAt = DateTime.Now;
                order.ProcessStatus = FlowerOrder.UNDER_PROCESS;
                
                orderManager.CreateOrder(order);
                // refetching just created order from db, 
                // since id property is required for the following logic
                order = orderManager.GetLastFlowerOrderFOrCustomer(user.Id);

                IList<ShoppingCartItem> cartItems = cartManager.GetItemsByCustomer(user.Id);
                foreach(ShoppingCartItem cartItem in cartItems)
                {
                    OrderItem orderItem = new OrderItem()
                    {
                        OrderId = order.Id,
                        FlowerId = cartItem.FlowerId,
                        Quantity = cartItem.Quantity
                    };
                    orderManager.CreateOrderItem(orderItem);
                    // delete cart item afterwards
                    cartManager.DeleteItem(cartItem.Id, user.Id);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

00003951_DBSD_CW2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Flowers</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Flowers", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Categories", "Index", "Home")</li>
                    <li>@Html.ActionLink("All Flowers", "Index", "Flower")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("My Orders", "Index", "Order")</li>
                    }
                    
                    <li>@Html.ActionLink("Report", "Purchases", "Report")</li>
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-right">
                        <ul class="nav navbar-nav">
                            <li><a>@User.Identity.Name</a></li>
                            <li><a href="/Cart"><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</a></li>
                            <li>@Html.ActionLink("Log Out", "LogOut", "Login", null, new { @class = "" })</li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="navbar-right">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Log in", "Index", "Login", null, new { @class = "" })</li>
                            <li>@Html.ActionLink("Register", "Register", "Login", null, new { @class = "" })</li>
                        </ul>
                    </div>
                }

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Flowers</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>